TEMPDICT_STORE_TICK = 0.1  # seconds
TEMPDICT_PICKLE_FILENAME = "picklefile"
TEMPDICT_GET_DICTIONARY_REATTEMPT = TEMPDICT_STORE_TICK


#<><><><><><> OLD DATA
APPLICATION_VERSION = '8.4.2'
IOS_VERSION = '13.5'
DEVICE_MODEL = 'iPhone11,8'
DEVICE_GROUP = 'iPhone'
DEVICE_ID = 'BDECF494-61DE-D6FB-0D64-52EE4112218A'
DATA_COMPRESSION = False
INTERFACE_UPDATE_TIMEOUT = 1000  # ms
TABLE_ROW_HEIGHT = 25
TABLE_MINIMUM_WIDTH = 25
WINDOW_NAME = "Arcadius"
LOGS_MAX_AMOUNT = 99

